config/routes.rb
            Rails.application.routes.draw do
  resources :comments
            mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
              match '/users',   to: 'users#index',   via: 'get'
              match '/users/:id',     to: 'users#show',       via: 'get'
              match '/memes/',        to: 'memes#index',      via: 'get'
              match '/memes/edit',        to: 'memes#edit',      via: 'get'
              match "/memes/edit",     to: 'memes#update',      via: 'post'



             


              devise_for :users, :path_prefix => 'd', controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
              

              resources  :pins do

                member do
                  put "like",    to: "pins#upvote"
                  put "dislike", to: "pins#downvote"
                end
              resources :comments
              end
              
              resources :users do
                member do
                  get :pins
                end
              end

              root "pins#index"
            end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :pin
	belongs_to :user
end
 

app/models/meme.rb
class Meme < ActiveRecord::Base
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments, dependent: :destroy

	has_attached_file :image, styles: { medium: "300x300>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
	  # Include default devise modules. Others available are:
	  # :confirmable, :lockable, :timeoutable and :omniauthable
	  devise :database_authenticatable, :registerable, :omniauthable, 
	         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:facebook]
	  has_many :pins, dependent: :destroy
	  
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, 
	 :default_url => "/images/:style/missing.png",  
	 :path => ":rails_root/public/images/:style/:filename",
	 :url => "/images/:style/:filename" 
	validates_attachment :avatar, content_type: { content_type: /\Aimage\/.*\Z/ }

def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
   
  end
end

	def password_required?
		super && provider.blank?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def create
    @pin = Pin.find(params[:pin_id])
    @comment = @pin.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @pin, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end








  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:pin_id, :body, :user_id)
    end
end 

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController

require 'open-uri'
require 'meme_captain'



def index
 @pins = Pin.all
end

def show

end

def edit

@pin = Pin.find(params[:pin])
@meme = @pin

end

def detroy

end

def create
@meme = Meme.new(params=[:meme])
if @meme.save
	redirect_to @pins

else
									
end
end

def new

@meme = @meme.new


end

def update



open('http://memecaptain.com/troll_face.jpg', 'rb') do |f|
  i = MemeCaptain.meme_top_bottom(f, :toptext, :bottomtext)
  i.display
  i.write('out.jpg')
end
redirect_to @memes
end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def all
		@user = User.from_omniauth(request.env["omniauth.auth"])
		if @user.persisted?
			sign_in_and_redirect @user, notice: "Signed In!"
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
	alias_method :facebook, :all
	
	def failure
		redirect_to root_path
	end
end

app/controllers/pins_controller.rb
						class PinsController < ApplicationController
							before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
							before_action :authenticate_user!, except: [:index, :show]

							def index
								@pins = Pin.all.order("created_at DESC")

							end

							def show

								

							end


							def new
								@pin = current_user.pins.build
							end

							def create
								@pin = current_user.pins.build(pin_params)

								if @pin.save
									redirect_to @pin, notice: "Successfully created new Pin"
								else
									render 'new'
								end
							end

							def edit
								if @pin.user != current_user
						       redirect_to root_path
						    end
							end

							def update
								if @pin.update(pin_params) && @pin.user == current_user
								 redirect_to @pin, notice: "Pin was successfully updated"
						    else
						       render 'edit'
						     end
							end

							def destroy
								if @pin.user == current_user
								@pin.destroy
								redirect_to root_path
								 else
								 redirect_to root_path, notice: "Not Your Pin!"
								 end	
							end

							def upvote
								@pin.upvote_by current_user
								redirect_to :back
							end

							def downvote
    							 @pin.downvote_from current_user
   								 redirect_to :back
							end


							private

							def pin_params
								params.require(:pin).permit(:title, :description, :image)
							end

							def find_pin
								@pin = Pin.find(params[:id])
							end
						end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find_by_id(params[:id])
  @pins = @user.pins.order("created_at DESC")
  
  end

  def pins
  	@user = User.find(params[:id])
  	@pins = @user.pins
  end

def user_params
  params.require(:user).permit(:avatar)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meme_helper.rb
module MemeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/OLD_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %> 

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %> 

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :pin_id
    = f.number_field :pin_id
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Pin
      %th Body
      %th User
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.pin_id
        %td= comment.body
        %td= comment.user
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Pin:
  = @comment.pin_id
%p
  %b Body:
  = @comment.body
%p
  %b User:
  = @comment.user

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Pin Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-invert
		.container
			<center>
			

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-invert
					%h2= link_to "Home", root_path
					%li= link_to "My Pins", user_path(current_user)
					%li= link_to "Users", users_path
					%li= link_to "New Pin", new_pin_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
					.nav.round-image-50= image_tag(current_user.avatar.url(:thumb))
					
			- else
				%ul.nav.navbar-nav.navbar-invert
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
					%h2.loginBtn.loginBtn--facebook= link_to "Login with FB", user_facebook_omniauth_authorize_path, id: "sign_in"
					%h2.loginBtn.loginBtn--google= link_to "Login with Google", root_path

		</center>
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"
		= yield

app/views/memes/_form.html.haml
= simple_form_for @meme, html: { multipart: true } do |f|
	- if @meme.errors.any?
		#errors
			%h2
				= pluralize(@meme.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @meme.errors.full_messages.each do |msg|
					%li= msg


	.form-group
		= f.input :toptext , input_html: { class: 'form-control', required: true }

	.form-group
		= f.input :bottomtext, :required => 'required' , input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/memes/edit.html.haml
= require 'open-uri'
= require 'meme_captain'

#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pin
			.panel-body
				<center>
				.current_image

					%strong.center Current Image

					= image_tag @pin.image.url(:medium)
					</center>
					= render '/memes/form'

app/views/memes/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url), pin
			%h2= link_to pin.title, pin
			%p.user
				Submitted by
				= pin.user.email
			= link_to "Make Meme", :controller => "memes", :action => "edit", :pin => pin.id
			
e

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
				= pluralize(@pin.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg
					



	.form-group
		= f.input :image, :required => 'required' , input_html: { class: 'form-control' }


	.form-group
		= f.input :title, :required => 'required' , input_html: { class: 'form-control' }

	.form-group
		= f.input :description, :required => 'required' , input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pin
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url), pin
			%h2= link_to pin.title, pin
			%p.user
				Submitted by
				= pin.user.email
			%p 
				= link_to dislike_pin_path(pin), method: :put, class: "btn btn-default" do
					%span.glyphicon.glyphicon-thumbs-down
					= pin.get_downvotes.size
				= pin.created_at.strftime("%B %d, %Y")
				= link_to like_pin_path(pin), method: :put, class: "btn btn-default" do
					%span.glyphicon.glyphicon-thumbs-up
					= pin.get_upvotes.size

app/views/pins/meme.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pin
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Create A New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
				= @pin.created_at.strftime("%B %d, %Y")
			.panel-footer
				.row
					.col-md-6
						%p.user
							Submitted by
							= @pin.user.email
							= social_share_button_tag(@pin.title)
					.col-md-6
						.btn-group.pull-right
							= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
								= @pin.get_upvotes.size
								
							- if user_signed_in?
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

			.panel-footer
				<center>


				- if user_signed_in?
					= render :partial => @pin.comments
					= simple_form_for [@pin, Comment.new]  do |f| 
						= f.text_area :body, class: "form-control"
						= f.submit "Add Comment", class: "btn btn-primary"

				</center>
 

app/views/users/index.html.erb
<center>
<div class="user_show">
<h1>Users</h1>


<% @users = User.all %>
<% @users.each do |user| %>
  <div>
  <p> <%= user.name %> </p>
  <p class="round-image", align="center"><%= image_tag(user.avatar.url(:thumb)) %></p>
  <p> <%= link_to user.email, user %><br/></p>
  </div>
  <p></p>
  
<% end %>

</div>
</center>

app/views/users/show.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			\#{link_to (image_tag pin.image.url), pin}
			%h2= link_to pin.title, pin
			- if user_signed_in?
				= link_to "Edit", edit_pin_path(pin), class: "btn btn-default"
				= link_to "Delete", pin_path(pin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
			%p.user
				Submitted by
				= pin.user.email
			%p 
				= pin.created_at.strftime("%B %d, %Y")